# Trustee Responsibilities

A. Trustee is responsible for providing the necessary legal, technical, and organizational infrastructure to support the creation, use, and maintenance of the Data Trust. In conjunction with the Data Trust Governance Board, Trustee will also ensure all Members, Users, Trustee and Trustee Affiliates are in compliance with the terms and conditions written herein. 

B. If data is classified as public (or the equivalent) and public access of public data is listed as an Approved Use, once public data is contributed by any member, Trustee shall have the right to immediately make public data publicly available as approved and specified herein.

C. Trustee agrees to keep all member-contributed data resources deemed by Member to be sensitive and/or personal information, and classified accordingly, from disclosure by any unauthorized party. 

D. Trustee agrees to only disclose member-contributed data resources to its employees and/or Trustee Affiliates who need access in order to meet Trustee’s obligations and requirements for the purposes contemplated by this Agreement. Further, Trustee represents and certifies that no Data Trust Member nor Third Party shall have access to Members’ member-contributed data resources in their raw form without express written or electronic approval by Member.

E. Trustee will ensure that no data identified and classified as personal information will be included in any published data.

F. Trustee will ensure Members have the opportunity to inspect aggregate trust-managed data resources to verify no data classified as sensitive or personal information is included before such data is published. 

G. Trustee’s designated Governance Board representative will serve as Chair of the Governance Board.

